### ISSUE TITLE
problem reading multipolygons and multilinestrings from MVT

### ISSUE THREAD

**Issue by Maroben** [geometalab/Vector-Tiles-Reader-QGIS-Plugin_2016#27]
Multipolygons and multilinestrings are not displayed, i.e. ignored by the OGR reader of QGIS.

**Comment by Maroben** [comment]
The mapzen/mapbox-vector-tile library does not support multi geometry types (multipoint, multilinestring, multipolygon). These exist at least in MBTiles from OSM2VectorTiles and most probably also from "MapBox Streets v7".

**Comment by nvkelso** [comment]
Tell me more, please?

**Comment by sfkeller** [comment]
We're missing handling of multi geometry types in mapzen/mapbox-vector-tile library . Are you by any chance working on any enhancements in this direction?

**Comment by nvkelso** [comment]
@sfkeller Are you using the [mapzen/mapbox-vector-tile](https://github.com/mapzen/mapbox-vector-tile) library to do the tile decoding and having a problem?

Or are you running into problems with mapzen's vector tile service?

/cc @zerebubuth and @rmarianski

**Comment by nvkelso** [comment]
Is the plugin in a far enough state for us to install and help debug? Are there instructions?

**Comment by sfkeller** [comment]
@nvkelso Many thanks for offering help! As of beginning of next week there will be a very first code which can be tested with some fiddling (Linux only). Then, the plugin can be downloaded as zip from this repo and installed manually in the plugins directory of QGIS. 

I changed this issue from bug to feature, since it's about extending your nice lib to multi-geometries. See https://github.com/geometalab/Vector-Tiles-Reader-QGIS-Plugin/blob/master/contrib/mapbox_vector_tile/decoder.py

**Comment by rmarianski** [comment]
Multipolygon decoding should work. What version of the library are you using? Can you try and see if it works with master?

**Comment by sfkeller** [comment]
@nvkelso @rmarianski We're experiencing a show stopper for QGIS under Windows using the mapzen/mapbox-vector-tile library since it's depending on module protobuf. See #18 . I've asked @pka to help sorting this out. 
@Maroben Can you pls. push your most recent code a.s.a.p. to this repo so that we can help testing?

**Comment by sfkeller** [comment]
The mapzen/mapbox-vector-tile library is correct regarding handling of multi-geometries. It's the client (this reader code) which has to handle multi-geometries if needed. See #31. Issue #18 regarding missing protobuf libs under Windows is still open, though.

**Comment by nvkelso** [comment]
Whew, that's a relief!
