### ISSUE TITLE
import using the gui

### ISSUE THREAD

**Issue by Maroben** [geometalab/Vector-Tiles-Reader-QGIS-Plugin_2016#4]
Use the GUI in gqis to import an mbtile

**Comment by Maroben** [comment]
eg file open dialog

**Comment by sfkeller** [comment]
Call the dialog "Add Vector Tiles Layer..." (deutsch "Vector Tiles Layer hinzufügen...")

**Comment by sfkeller** [comment]
Remember file path, so next time the dialog is opened, the same path is set as lest time (see GeoCSV plugin).

**Comment by sfkeller** [comment]
1. Choose good Layer name from metadata.
2. Take whaterever metadata is available from VT source.
3. Add Layer to the bottom of the Layer list (not the top), since currently VT are base maps.

See QuickMapServices for a good handling of base map layers: https://github.com/nextgis/quickmapservices
QuickMapServices is also very well programmed Python plugin!

**Comment by Maroben** [comment]
for last comment opened a new issue #11
